### ISSUE TITLE
Add info about TDD or remove question from diagnostic

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/rails-api-bdd#14]
The diagnostic asks to compare and contrast BDD and TDD.

**Comment by jrhorn424** [comment]
It should be added to the README.

Here's what I'm looking for:

-   TDD means writing tests before you write implementation code.
-   Automated tests can be written after you write implementation code. This is called "backfilling".
-   TDD is hard when you're learning. If you want a challenge, go for it. A more attainable challenge is to backfill if you're able to on your project.
-   BDD is top-down testing. It can be done either before or after, so BDD can be done as part of TDD, or as backfilling. BDD is about writing a feature (a fancy `curl` request written in Ruby) and having that initiate an error (a routing error), then writing a unit that shows the same error (a routing unit test), then writing the code that passes it, then running the feature, seeing a new error, etc...

BDD is basically how we're teaching all of rails now, in an ideal delivery.
