### ISSUE TITLE
Ensure rails-api-bdd-iteration is fully integrated

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/rails-api-bdd#16]
This repository should be the base, and `-iteration` may be archived.

Only after combining, descope.

**Comment by raq929** [comment]
#7 implies that they were combined. Is there something missing? Does this lesson need descoping? I thought it went well in 015.

**Comment by jrhorn424** [comment]
I believe I was confused due to the objectives, and this issue was opened because someone asked about descoping. 

I wanted to ensure anything needed from `-iteration` was included: remaining issues, tests (which you were asking about yesterday), and solution code.

**Comment by raq929** [comment]
The issues are no longer outstanding in this repo, and the solution code is included, so I think this can be closed when `016/master` and `016/solution` are merged.

**Comment by raq929** [comment]
I have archived ga-wdi-boston-attic/rails-api-bdd-iteration
