### ISSUE TITLE
Does not support HTTPS

### ISSUE THREAD

**Issue by erdesi90562** [ga-wdi-boston/rails-api-bdd#2]
/gem.rb
```Ruby
gem 'rails-api', git: 'git@github.com:rails-api/rails-api.git'
gem 'active_model_serializers', git: 'git@github.com:rails-api/active_model_serializers.git'
```

Updated for support for HTTPS
/gem.rb
```Ruby
gem 'rails-api', git: 'https://github.com/rails-api/rails-api.git'
gem 'active_model_serializers', git: 'https://github.com/rails-api/active_model_serializers.git'
```

Support for both would be great.

**Comment by jrhorn424** [comment]
I don't believe this is valid. @gaand care to comment?

**Comment by gaand** [comment]
@jrhorn424: @erdesi90562 uses two factor auth.  I'd guess he doesn't have an ssh key loaded and so can't use the ssh url.

**Comment by jrhorn424** [comment]
@erdesi90562 You need to setup SSH access and use SSH urls when you clone.
